// Compile-time contract between the hand-written client types and the backend's
// OpenAPI schema (schema.gen.ts). Nothing here runs: `npm run build` fails when
// a response no longer fits the type the UI reads it through, or when a payload
// the UI sends no longer fits what the endpoint accepts.

import type * as Api from './schema.gen'
import type {
  Account,
  AccountCreatePayload,
  AccountSummary,
  AppVersion,
  AssistantConversation,
  AssistantConversationDetail,
  AssistantMessage,
  AssistantSettings,
  AssistantSettingsPayload,
  AssistantStatus,
  AssistantSuggestions,
  AssistantToolCall,
  AssistantUsage,
  AssistantUsageDay,
  AssistantUsagePeriod,
  AuthStatus,
  AuthUser,
  BackupDocument,
  BackupImportSummary,
  CashflowItem,
  CashflowSummary,
  CashInvestedSplit,
  Category,
  CategoryPatch,
  CategorySummary,
  CombinedOverview,
  CombinedOverviewAssetClassSlice,
  CombinedOverviewProvider,
  CombinedOverviewProviderSlice,
  ConfirmRequest,
  ContributionEvent,
  DaySummary,
  DrawdownOut,
  EuriborPoint,
  EuriborSeries,
  FidelityEvolution,
  FidelityImportConfirmResult,
  FidelityImportPreview,
  FidelityImportPreviewLot,
  FidelityKpis,
  FidelityLot,
  FidelityLots,
  FidelityReminderResponse,
  ImportQuality,
  ImportQualityRowFlag,
  ImportQualitySignal,
  ImportQualitySummary,
  ImportResult,
  ImportSummaryJob,
  ImportSummarySettings,
  ImportSummarySettingsPayload,
  ImportTransaction,
  InvestmentConnection,
  InvestmentHolding,
  InvestmentPlugin,
  InvestmentPortfolio,
  InvestmentReturns,
  MerchantSummary,
  MonthlyReturnRow,
  MonthSummary,
  Mortgage,
  MortgageBalancePoint,
  MortgageBonus,
  MortgageCharts,
  MortgageInput,
  MortgageNetWorth,
  MortgageOverview,
  MortgagePaymentCandidate,
  MortgagePaymentCandidates,
  MortgagePrepayment,
  MortgagePrepaymentInput,
  MortgageRatePeriod,
  MortgageReconciliation,
  MortgageReconciliationRow,
  MortgageSchedule,
  MortgageScheduleRow,
  MortgageScheduleYear,
  MortgageSimulation,
  MortgageSimulationRequest,
  MortgageSimulationSide,
  MortgageSummary,
  NotificationChannelOut,
  NotificationOut,
  Overview,
  PreviewResponse,
  Rule,
  RuleInput,
  RulePatch,
  StatementMonth,
  StatementOriginal,
  StatementReminder,
  SummaryMonths,
  Tag,
  TelegramChannelIn,
  TelegramTestIn,
  TelegramTestOut,
  Transaction,
  TransactionPage,
  TransactionPatch,
  ValidateAccountsResponse,
  ValidatedAccount,
  ValuePoint,
} from './types'

/** The backend's response must be assignable to the type the UI reads. */
type Satisfies<Backend extends Frontend, Frontend> = Backend
/** The payload the UI sends must be assignable to what the endpoint accepts. */
type Accepts<Backend, Frontend extends Backend> = Frontend

// A backup restore writes any string into these, so a stored rule can carry a
// mode the typed rule form does not know; the form narrows them itself.
type RuleModeKeys = 'description_mode' | 'detail_mode' | 'amount_sign'

export type ResponseContract = [
  // ─── Ledger ──────────────────────────────────────────────────────────────
  Satisfies<Api.AccountOut, Account>,
  Satisfies<Api.CategoryOut, Category>,
  Satisfies<Api.TagOut, Tag>,
  Satisfies<Api.TransactionOut, Transaction>,
  Satisfies<Api.TransactionPage, TransactionPage>,
  Satisfies<Omit<Api.RuleOut, RuleModeKeys>, Omit<Rule, RuleModeKeys>>,

  // ─── Summaries ───────────────────────────────────────────────────────────
  Satisfies<Api.TransactionMonthsOut, SummaryMonths>,
  Satisfies<Api.OverviewOut, Overview>,
  Satisfies<Api.ByCategoryRow, CategorySummary>,
  Satisfies<Api.ByMonthRow, MonthSummary>,
  Satisfies<Api.ByDayRow, DaySummary>,
  Satisfies<Api.ByAccountRow, AccountSummary>,
  Satisfies<Api.ByMerchantRow, MerchantSummary>,
  Satisfies<Api.CashflowOut, CashflowSummary>,
  Satisfies<Api.CashflowCategoryRow, CashflowItem>,

  // ─── Imports and statements ──────────────────────────────────────────────
  Satisfies<Api.PreviewOut, PreviewResponse>,
  Satisfies<Api.ExtractedTransactionOutput, ImportTransaction>,
  Satisfies<Api.ImportResult, ImportResult>,
  Satisfies<Api.ImportQuality, ImportQuality>,
  Satisfies<Api.ImportQualitySummary, ImportQualitySummary>,
  Satisfies<Api.ImportQualitySignal, ImportQualitySignal>,
  Satisfies<Api.ImportQualityRowFlag, ImportQualityRowFlag>,
  Satisfies<Api.StatementMonth, StatementMonth>,
  Satisfies<Api.StatementOriginal, StatementOriginal>,
  Satisfies<Api.StatementReminderOut, StatementReminder>,
  Satisfies<Api.ImportSummary, BackupImportSummary>,

  // ─── Auth and app ────────────────────────────────────────────────────────
  Satisfies<Api.StatusResponse, AuthStatus>,
  Satisfies<Api.AuthResponse, AuthUser>,
  Satisfies<Api.VersionOut, AppVersion>,

  // ─── Investments ─────────────────────────────────────────────────────────
  Satisfies<Api.InvestmentPluginOut, InvestmentPlugin>,
  Satisfies<Api.ConnectionOut, InvestmentConnection>,
  Satisfies<Api.DiscoveredAccountOut, ValidatedAccount>,
  Satisfies<Api.ValidateTokenResponse, ValidateAccountsResponse>,
  Satisfies<Api.InvestmentPortfolioOut, InvestmentPortfolio>,
  Satisfies<Api.InvestmentReturns, InvestmentReturns>,
  Satisfies<Api.InvestmentHoldingOut, InvestmentHolding>,
  Satisfies<Api.ContributionEventOut, ContributionEvent>,
  Satisfies<Api.ValuePoint, ValuePoint>,
  Satisfies<Api.MonthlyReturnRow, MonthlyReturnRow>,
  Satisfies<Api.DrawdownOut, DrawdownOut>,
  Satisfies<Api.CashInvestedSplit, CashInvestedSplit>,
  Satisfies<Api.CombinedOverviewOut, CombinedOverview>,
  Satisfies<Api.ProviderAllocationItem, CombinedOverviewProviderSlice>,
  Satisfies<Api.AssetClassAllocationItem, CombinedOverviewAssetClassSlice>,
  Satisfies<Api.ProviderCardOut, CombinedOverviewProvider>,

  // ─── Fidelity ────────────────────────────────────────────────────────────
  Satisfies<Api.FidelityReminderOut, FidelityReminderResponse>,
  Satisfies<Api.FidelityKpisOut, FidelityKpis>,
  Satisfies<Api.FidelityEvolutionOut, FidelityEvolution>,
  Satisfies<Api.FidelityLotOut, FidelityLot>,
  Satisfies<Api.FidelityLotsOut, FidelityLots>,
  Satisfies<Api.FidelityPreviewLotOut, FidelityImportPreviewLot>,
  Satisfies<Api.FidelityPreviewOut, FidelityImportPreview>,
  Satisfies<Api.FidelityImportResult, FidelityImportConfirmResult>,

  // ─── Notifications ───────────────────────────────────────────────────────
  Satisfies<Api.NotificationOut, NotificationOut>,
  Satisfies<Api.NotificationChannelOut, NotificationChannelOut>,
  Satisfies<Api.TelegramTestOut, TelegramTestOut>,
  Satisfies<Api.ImportSummarySettingsOut, ImportSummarySettings>,
  Satisfies<Api.ImportSummaryJobOut, ImportSummaryJob>,

  // ─── Assistant ───────────────────────────────────────────────────────────
  Satisfies<Api.AssistantStatusOut, AssistantStatus>,
  Satisfies<Api.AssistantSuggestionsOut, AssistantSuggestions>,
  Satisfies<Api.AssistantToolCall, AssistantToolCall>,
  Satisfies<Api.AssistantMessageOut, AssistantMessage>,
  Satisfies<Api.AssistantConversationOut, AssistantConversation>,
  Satisfies<Api.AssistantConversationDetailOut, AssistantConversationDetail>,
  Satisfies<Api.AssistantSettingsOut, AssistantSettings>,
  Satisfies<Api.AssistantUsageOut, AssistantUsage>,
  Satisfies<Api.AssistantUsagePeriod, AssistantUsagePeriod>,
  Satisfies<Api.AssistantUsageDay, AssistantUsageDay>,

  // ─── Mortgage ────────────────────────────────────────────────────────────
  Satisfies<Api.MortgageOut, Mortgage>,
  Satisfies<Api.RatePeriodOut, MortgageRatePeriod>,
  Satisfies<Api.BonusOut, MortgageBonus>,
  Satisfies<Api.PrepaymentOut, MortgagePrepayment>,
  Satisfies<Api.MortgageSummary, MortgageSummary>,
  Satisfies<Api.MortgageOverview, MortgageOverview>,
  Satisfies<Api.ScheduleOut, MortgageSchedule>,
  Satisfies<Api.ScheduleRowOut, MortgageScheduleRow>,
  Satisfies<Api.ScheduleYearOut, MortgageScheduleYear>,
  Satisfies<Api.MortgageChartsOut, MortgageCharts>,
  Satisfies<Api.BalancePointOut, MortgageBalancePoint>,
  Satisfies<Api.EuriborSeriesOut, EuriborSeries>,
  Satisfies<Api.EuriborPointOut, EuriborPoint>,
  Satisfies<Api.ReconciliationOut, MortgageReconciliation>,
  Satisfies<Api.ReconciliationRowOut, MortgageReconciliationRow>,
  Satisfies<Api.SimulationOut, MortgageSimulation>,
  Satisfies<Api.SimulationSideOut, MortgageSimulationSide>,
  Satisfies<Api.MortgageNetWorthOut, MortgageNetWorth>,
  Satisfies<Api.PaymentCandidatesOut, MortgagePaymentCandidates>,
  Satisfies<Api.PaymentCandidateOut, MortgagePaymentCandidate>,
]

export type RequestContract = [
  Accepts<Api.AccountCreate, AccountCreatePayload>,
  Accepts<Api.CategoryUpdate, CategoryPatch>,
  Accepts<Api.TransactionUpdate, TransactionPatch>,
  Accepts<Api.ConfirmIn, ConfirmRequest>,
  Accepts<Api.ExtractedTransactionInput, ImportTransaction>,
  Accepts<Api.RuleIn, RuleInput>,
  Accepts<Api.RuleUpdate, RulePatch>,
  Accepts<Api.BackupDocument, BackupDocument>,
  Accepts<Api.TelegramChannelIn, TelegramChannelIn>,
  Accepts<Api.TelegramTestIn, TelegramTestIn>,
  Accepts<Api.ImportSummarySettingsIn, ImportSummarySettingsPayload>,
  Accepts<Api.AssistantSettingsIn, AssistantSettingsPayload>,
  Accepts<Api.MortgageCreate, MortgageInput>,
  Accepts<Api.MortgageUpdate, MortgageInput>,
  Accepts<Api.PrepaymentIn, MortgagePrepaymentInput>,
  Accepts<Api.SimulationRequest, MortgageSimulationRequest>,
]
