// GENERATED by scripts/gen-api-types.mjs from openapi.json. Do not edit.
//
// Regenerate after any change to the backend's schemas:
//   python scripts/export_openapi.py   (repo root)
//   npm run gen:api                    (frontend/)
//
// Every property of a schema reachable from a response is required: FastAPI
// serialises every field, while Pydantic leaves a defaulted one out of the
// spec's "required". A schema shared with a request follows the same rule;
// request-only schemas keep the spec's optionality.

export interface AccountCreate {
  account_number?: string | null
  currency?: string
  name: string
  opening_balance?: number | null
  opening_date?: string | null
  type?: string
}

export interface AccountOut {
  account_number_masked: string | null
  currency: string
  id: number
  name: string
  tx_count: number
  type: string | null
}

export interface AccountPatch {
  name: string
}

export interface AssetClassAllocationItem {
  asset_class: string
  label: string
  pct: number
  value_eur: number
}

export interface AssistantConversationDetailOut {
  created_at: string
  id: number
  messages: AssistantMessageOut[]
  title: string
  updated_at: string
}

export interface AssistantConversationOut {
  created_at: string
  id: number
  title: string
  updated_at: string
}

export interface AssistantMessageIn {
  content: string
}

export interface AssistantMessageOut {
  content: string
  created_at: string
  id: number
  role: 'user' | 'assistant'
  tool_calls: AssistantToolCall[] | null
}

export interface AssistantSettingsIn {
  custom_instructions?: string | null
  monthly_token_budget?: number | null
  rate_limit_messages?: number | null
  rate_limit_window_seconds?: number | null
  system_prompt?: string | null
}

export interface AssistantSettingsOut {
  custom_instructions: string | null
  default_system_prompt: string
  effective_rate_limit_messages: number
  effective_rate_limit_window_seconds: number
  max_custom_instructions_chars: number
  max_system_prompt_chars: number
  missing_safety_markers: string[]
  monthly_token_budget: number | null
  rate_limit_messages: number | null
  rate_limit_window_seconds: number | null
  system_prompt: string | null
}

export interface AssistantStatusOut {
  enabled: boolean
  reason: string | null
}

export interface AssistantSuggestionsOut {
  suggestions: string[]
}

export interface AssistantToolCall {
  arguments: string
  name: string
  ok: boolean
}

export interface AssistantUsageDay {
  day: string
  messages: number
  summaries: number
  tokens: number
}

export interface AssistantUsageOut {
  all_time: AssistantUsagePeriod
  budget_remaining: number | null
  by_day: AssistantUsageDay[]
  monthly_token_budget: number | null
  this_month: AssistantUsagePeriod
  usage_available: boolean
}

export interface AssistantUsagePeriod {
  completion_tokens: number
  messages: number
  prompt_tokens: number
  summaries: number
  total_tokens: number
}

export interface AuthResponse {
  message: string
  username: string
}

export interface BackupAccountIn {
  currency: string
  name: string
  type: string
}

export interface BackupCategoryIn {
  color: string
  is_base: boolean
  name: string
  name_es?: string | null
}

export interface BackupDocument {
  accounts?: BackupAccountIn[]
  categories?: BackupCategoryIn[]
  exported_at: string
  finlytics_backup_version: number
  investments?: BackupInvestmentsIn | null
  rules?: BackupRuleIn[]
  tags?: BackupTagIn[]
  transactions?: BackupTransactionIn[]
}

export interface BackupEsppLotIn {
  connection_plugin_id?: string
  cost_basis: number
  cost_basis_per_share: number
  dedup_hash: string
  grant_date?: string | null
  holding_period?: string | null
  purchase_date: string
  share_source: string
  shares: number
  source_currency: string
  ticker?: string
}

export interface BackupInvestmentConnectionIn {
  account_label_masked?: string | null
  last_synced_at?: string | null
  plugin_id: string
  status?: string
  token_enc?: string | null
}

export interface BackupInvestmentsIn {
  connections?: BackupInvestmentConnectionIn[]
  espp_lots?: BackupEsppLotIn[]
  price_history?: BackupPriceHistoryIn[]
}

export interface BackupPriceHistoryIn {
  close_eur: number
  close_usd: number
  fx_eur_usd: number
  price_date: string
  ticker: string
}

export interface BackupRuleIn {
  account_ref?: string | null
  add_tags?: string[]
  amount_max?: number | null
  amount_min?: number | null
  amount_sign?: string | null
  currency?: string | null
  description_mode: string
  description_value: string
  detail_mode?: string | null
  detail_value?: string | null
  enabled?: boolean
  name: string
  priority?: number
  set_category?: string | null
  set_merchant?: string | null
  skip_ai?: boolean
}

export interface BackupTagIn {
  color: string
  emoji?: string | null
  name: string
}

export interface BackupTransactionIn {
  account: string
  amount: number
  balance_after?: number | null
  category?: string | null
  category_confidence?: number | null
  currency: string
  description: string
  detail?: string | null
  duplicate_key?: string | null
  is_system?: boolean
  merchant?: string | null
  tags?: string[]
  transaction_date: string
}

export interface BalancePointOut {
  balance: number
  date: string
  projected: boolean
}

export interface Body_create_import_api_imports_post {
  account_id?: number | null
  account_name?: string | null
  file: Blob
}

export interface Body_fidelity_import_confirm_api_investments_fidelity_import_confirm_post {
  file: Blob
}

export interface Body_fidelity_import_preview_api_investments_fidelity_import_preview_post {
  file: Blob
}

export interface Body_preview_import_api_imports_preview_post {
  account_name?: string | null
  file: Blob
}

export interface BonusIn {
  active?: boolean
  annual_cost?: number
  end_date?: string | null
  name: string
  spread_reduction?: number
  start_date?: string | null
}

export interface BonusOut {
  active: boolean
  annual_cost: number
  end_date: string | null
  id: number
  name: string
  spread_reduction: number
  start_date: string | null
}

export interface ByAccountRow {
  account: string
  currency: string
  expense: number
  income: number
  net: number
}

export interface ByCategoryRow {
  amount: number
  category: string
  category_id: number
  count: number
}

export interface ByDayRow {
  day: string
  expense: number
  income: number
  net: number
}

export interface ByMerchantRow {
  amount: number
  count: number
  merchant: string
}

export interface ByMonthRow {
  expense: number
  income: number
  month: string
  net: number
}

export interface CashInvestedSplit {
  cash_amount: number
  instruments_amount: number
  instruments_cost: number
  total_amount: number
}

export interface CashflowCategoryRow {
  amount: number
  category: string
}

export interface CashflowOut {
  currency: string
  expense: CashflowCategoryRow[]
  income: CashflowCategoryRow[]
  total_expense: number
  total_income: number
}

export interface CategoryCreate {
  color?: string | null
  name: string
}

export interface CategoryOut {
  color: string
  id: number
  is_base: boolean
  name: string
  name_es: string | null
  tx_count: number
}

export interface CategoryUpdate {
  color?: string | null
}

export interface CheckDuplicatesIn {
  account_name: string
  transactions: CheckDuplicatesItem[]
}

export interface CheckDuplicatesItem {
  amount: number | string
  description: string
  detail?: string | null
  transaction_date: string
}

export interface CheckDuplicatesOut {
  is_duplicate: boolean[]
}

export interface CombinedOverviewOut {
  by_asset_class: AssetClassAllocationItem[]
  by_provider: ProviderAllocationItem[]
  partial: boolean
  providers: ProviderCardOut[]
  total_gain_loss_eur: number | null
  total_gain_loss_pct: number | null
  total_invested_eur: number | null
  total_value_eur: number
}

export interface ConfirmIn {
  account_name?: string | null
  account_number?: string | null
  opening_balance?: number | null
  source_filename: string
  source_pdf_base64?: string | null
  tag_colors?: Record<string, string> | null
  transactions: ExtractedTransactionInput[]
}

export interface ConnectCreate {
  account_numbers: string[]
  token: string
}

export interface ConnectionOut {
  account_label_masked: string | null
  created_at: string
  id: number
  last_synced_at: string | null
  plugin_id: string
  status: string
}

export interface ContributionEventOut {
  amount: number
  cumulative: number
  date: string
  type: 'contribution' | 'withdrawal'
}

export interface DeleteAccountResult {
  deleted: number
}

export interface DeleteMonthResult {
  deleted: number
}

export interface DiscoveredAccountOut {
  account_number: string
  account_number_masked: string
  status: string
  type: string
}

export interface DrawdownOut {
  end_date: string
  max_drawdown: number
  max_drawdown_eur: number
  start_date: string
}

export interface EuriborPointOut {
  period: string
  rate: number
}

export interface EuriborSeriesOut {
  index_name: string
  latest: number | null
  latest_period: string | null
  points: EuriborPointOut[]
}

export interface ExtractedTransactionInput {
  account_ref: string
  allow_duplicate?: boolean
  amount: number | string
  balance_after?: number | string | null
  category: string
  category_confidence?: number | null
  currency?: string
  description: string
  detail?: string | null
  matched_rule_id?: number | null
  matched_rule_name?: string | null
  merchant?: string | null
  raw_line?: string | null
  tags?: string[]
  transaction_date: string
}

export interface ExtractedTransactionOutput {
  account_ref: string
  allow_duplicate: boolean
  amount: number
  balance_after: number | null
  category: string
  category_confidence: number | null
  currency: string
  description: string
  detail: string | null
  matched_rule_id: number | null
  matched_rule_name: string | null
  merchant: string | null
  raw_line: string | null
  tags: string[]
  transaction_date: string
}

export interface FidelityEvolutionOut {
  contributions_series: ValuePoint[]
  value_series: ValuePoint[]
}

export interface FidelityImportResult {
  duplicates: number
  inserted: number
}

export interface FidelityKpisOut {
  as_of_date: string
  current_value_eur: number | null
  gain_loss_eur: number | null
  gain_loss_pct: number | null
  invested_eur: number
  last_price_date: string | null
  msft_price_usd: number | null
  price_stale: boolean
  total_shares: number
  usd_eur_rate: number | null
}

export interface FidelityLotOut {
  cost_basis_per_share_eur: number
  cost_basis_total_eur: number
  current_value_eur: number | null
  gain_loss_eur: number | null
  gain_loss_pct: number | null
  grant_date: string | null
  id: number
  purchase_date: string
  share_source: string
  shares: number
}

export interface FidelityLotsOut {
  lots: FidelityLotOut[]
}

export interface FidelityPreviewLotOut {
  cost_basis_per_share_eur: number
  cost_basis_total_eur: number
  grant_date: string | null
  purchase_date: string
  share_source: string
  shares: number
  source_currency: string
}

export interface FidelityPreviewOut {
  duplicate_count: number
  file_already_imported: boolean
  new_lots: FidelityPreviewLotOut[]
  source_currency: string
  total_in_file: number
}

export interface FidelityReminderOut {
  expected_date: string | null
  last_lot_date: string | null
  overdue: boolean
  period_label: string | null
}

export interface HTTPValidationError {
  detail: ValidationError[]
}

export interface ImportQuality {
  row_flags: ImportQualityRowFlag[]
  signals: ImportQualitySignal[]
  summary: ImportQualitySummary
}

export interface ImportQualityRowFlag {
  code: 'low_confidence_category' | 'missing_category' | 'generic_category' | 'missing_merchant' | 'zero_amount' | 'date_year_mismatch' | 'year_undetected' | 'intra_batch_duplicate'
  fields: string[]
  row_index: number
  severity: 'error' | 'warning' | 'info'
}

export interface ImportQualitySignal {
  code: 'low_confidence_category' | 'missing_category' | 'generic_category' | 'missing_merchant' | 'zero_amount' | 'date_year_mismatch' | 'year_undetected' | 'intra_batch_duplicate'
  count: number
  severity: 'error' | 'warning' | 'info'
}

export interface ImportQualitySummary {
  error_count: number
  flagged_row_count: number
  info_count: number
  warning_count: number
}

export interface ImportResult {
  import_run_id: number
  num_duplicates: number
  num_inserted: number
  num_parsed: number
  summary_job_id: number | null
}

export interface ImportSummary {
  accounts_created: number
  accounts_existing: number
  categories_created: number
  categories_updated: number
  espp_lots_duplicates: number
  espp_lots_inserted: number
  investment_connections_created: number
  investment_connections_updated: number
  price_history_duplicates: number
  price_history_inserted: number
  rules_created: number
  rules_updated: number
  tags_created: number
  tags_updated: number
  transactions_duplicates: number
  transactions_inserted: number
}

export interface ImportSummaryJobOut {
  account_name: string
  created_at: string
  error: string | null
  from_date: string
  id: number
  import_run_id: number | null
  language: 'en' | 'es'
  sent_at: string | null
  status: 'pending' | 'generating' | 'ready' | 'sending' | 'sent' | 'blocked' | 'failed' | 'uncertain' | 'cancelled'
  to_date: string
}

export interface ImportSummaryRetryIn {
  acknowledge_uncertain?: boolean
}

export interface ImportSummarySettingsIn {
  channel_id?: number | null
  enabled?: boolean
  language?: 'en' | 'es'
}

export interface ImportSummarySettingsOut {
  ai_available: boolean
  channel_id: number | null
  enabled: boolean
  language: 'en' | 'es'
}

export interface InvestmentHoldingOut {
  asset_class: string
  cost_basis: number | null
  currency: string
  current_value: number
  gain_loss: number | null
  gain_loss_pct: number | null
  last_updated: string
  name: string
  plugin_id: string
  ticker: string | null
  units: number | null
}

export interface InvestmentPluginOut {
  auth_type: 'api_key' | 'oauth' | 'token' | 'none'
  description: string
  icon: string
  id: string
  import_route: string | null
  name: string
  status: 'coming_soon' | 'available' | 'connected' | 'error'
  supported_features: string[]
}

export interface InvestmentPortfolioOut {
  accounts_unavailable: number
  cache_stale: boolean
  cached_at: string | null
  cash_invested: CashInvestedSplit | null
  contribution_events: ContributionEventOut[]
  contributions_series: ValuePoint[]
  currency: string
  drawdown: DrawdownOut | null
  holdings: InvestmentHoldingOut[]
  last_updated: string | null
  monthly_returns: MonthlyReturnRow[] | null
  plugins_connected: number
  returns: InvestmentReturns | null
  total_gain_loss: number | null
  total_gain_loss_pct: number | null
  total_invested: number | null
  total_value: number
  value_series: ValuePoint[]
}

export interface InvestmentReturns {
  aportaciones: number | null
  invested: number | null
  money_return: number | null
  money_return_annual: number | null
  pl: number | null
  rentabilidad_eur: number | null
  rentabilidad_pct: number | null
  retenciones: number | null
  sharpe_ratio: number | null
  twr_annual: number | null
  twr_last_month: number | null
  twr_last_week: number | null
  twr_last_year: number | null
  twr_total: number | null
  volatility: number | null
  xirr: number | null
}

export interface LoginIn {
  password: string
  remember?: boolean
  username: string
}

export interface MonthlyReturnRow {
  benchmark_pct: number | null
  months_eur: Record<string, number | null>
  months_pct: Record<string, number | null>
  total_eur: number | null
  total_pct: number | null
  year: number
}

export interface MortgageChartsOut {
  balance: BalancePointOut[]
  composition: ScheduleYearOut[]
}

export interface MortgageCreate {
  bonuses?: BonusIn[]
  include_in_net_worth?: boolean
  initial_principal: number
  lender?: string | null
  linked_account_id?: number | null
  linked_category_id?: number | null
  name: string
  notes?: string | null
  payment_day?: number
  property_value?: number | null
  property_value_date?: string | null
  rate_periods: RatePeriodIn[]
  rate_type: 'fixed' | 'variable' | 'mixed'
  signature_date?: string | null
  start_date: string
  term_months: number
}

export interface MortgageNetWorthOut {
  count: number
  net_contribution: number
  outstanding_debt: number
  property_value: number
}

export interface MortgageOut {
  bonuses: BonusOut[]
  id: number
  include_in_net_worth: boolean
  initial_principal: number
  lender: string | null
  linked_account_id: number | null
  linked_category_id: number | null
  name: string
  notes: string | null
  payment_day: number
  prepayments: PrepaymentOut[]
  property_value: number | null
  property_value_date: string | null
  rate_periods: RatePeriodOut[]
  rate_type: 'fixed' | 'variable' | 'mixed'
  signature_date: string | null
  start_date: string
  term_months: number
}

export interface MortgageOverview {
  amortized_principal: number
  annual_bonus_cost: number
  current_payment: number
  current_rate: number
  end_date: string | null
  has_projection: boolean
  id: number
  include_in_net_worth: boolean
  initial_principal: number
  interest_paid: number
  interest_remaining: number
  interest_saved: number
  lender: string | null
  linked_account_id: number | null
  linked_category_id: number | null
  ltv_pct: number | null
  months_elapsed: number
  months_remaining: number
  months_saved: number
  name: string
  next_payment_date: string | null
  original_end_date: string | null
  outstanding_balance: number
  progress_pct: number
  property_value: number | null
  rate_type: 'fixed' | 'variable' | 'mixed'
  total_cost: number
  total_interest: number
  total_prepaid: number
}

export interface MortgageSummary {
  id: number
  lender: string | null
  monthly_payment: number
  name: string
  outstanding_balance: number
  progress_pct: number
  rate_type: 'fixed' | 'variable' | 'mixed'
}

export interface MortgageUpdate {
  bonuses?: BonusIn[]
  include_in_net_worth?: boolean
  initial_principal: number
  lender?: string | null
  linked_account_id?: number | null
  linked_category_id?: number | null
  name: string
  notes?: string | null
  payment_day?: number
  property_value?: number | null
  property_value_date?: string | null
  rate_periods: RatePeriodIn[]
  rate_type: 'fixed' | 'variable' | 'mixed'
  signature_date?: string | null
  start_date: string
  term_months: number
}

export interface NotificationChannelOut {
  channel: string
  created_at: string
  enabled: boolean
  id: number
  label: string | null
}

export interface NotificationOut {
  action_link: string | null
  body_args: Record<string, unknown> | null
  body_key: string | null
  created_at: string
  dismissed_at: string | null
  id: number
  read_at: string | null
  severity: string
  source: string
  title_args: Record<string, string>
  title_key: string
  type: string
}

export interface OverviewOut {
  currency: string
  net: number
  num_transactions: number
  top_category: TopCategory | null
  total_expense: number
  total_income: number
}

export interface PasswordChangeIn {
  current_password: string
  new_password: string
}

export interface PaymentCandidateOut {
  account_id: number
  account_name: string
  amount: number
  category_id: number | null
  category_name: string | null
  deviation: number | null
  deviation_pct: number | null
  first_seen: string
  last_seen: string
  occurrences: number
}

export interface PaymentCandidatesOut {
  candidates: PaymentCandidateOut[]
  expected_payment: number | null
}

export interface PrepaymentIn {
  amount: number
  fee?: number
  mode: 'reduce_term' | 'reduce_payment'
  notes?: string | null
  payment_date: string
}

export interface PrepaymentOut {
  amount: number
  fee: number
  id: number
  mode: 'reduce_term' | 'reduce_payment'
  notes: string | null
  payment_date: string
}

export interface PreviewOut {
  account_ref: string | null
  detected_account_iban: string | null
  detected_account_masked: string | null
  filename: string
  matched_account_id: number | null
  matched_account_name: string | null
  quality: ImportQuality
  statement_year: number | null
  suggested_tags: SuggestedTag[]
  transactions: ExtractedTransactionOutput[]
  year_detected: boolean
}

export interface ProviderAllocationItem {
  label: string
  pct: number
  provider: string
  value_eur: number
}

export interface ProviderCardOut {
  gain_loss_eur: number | null
  gain_loss_pct: number | null
  icon: string
  id: string
  name: string
  route: string
  value_eur: number | null
}

export interface RatePeriodIn {
  cap_rate?: number | null
  fixed_rate?: number | null
  floor_rate?: number | null
  index_name?: string | null
  kind: 'fixed' | 'variable'
  review_lag_months?: number
  review_months?: number | null
  spread?: number | null
  start_month?: number
}

export interface RatePeriodOut {
  cap_rate: number | null
  fixed_rate: number | null
  floor_rate: number | null
  id: number
  index_name: string | null
  kind: 'fixed' | 'variable'
  review_lag_months: number
  review_months: number | null
  spread: number | null
  start_month: number
}

export interface ReadAllOut {
  updated: number
}

export interface ReconciliationOut {
  account_id: number | null
  category_id: number | null
  linked: boolean
  mortgage_id: number
  rows: ReconciliationRowOut[]
  total_actual: number
  total_expected: number
}

export interface ReconciliationRowOut {
  actual: number | null
  deviation: number | null
  deviation_pct: number | null
  expected: number
  matched: boolean
  period: string
}

export interface RuleApplyResult {
  applied: number
}

export interface RuleIn {
  account_ref?: string | null
  add_tags?: string[]
  amount_max?: number | null
  amount_min?: number | null
  amount_sign?: 'negative' | 'positive' | null
  currency?: string | null
  description_mode: 'contains' | 'starts_with' | 'exact' | 'regex'
  description_value: string
  detail_mode?: 'contains' | 'starts_with' | 'exact' | 'regex' | null
  detail_value?: string | null
  enabled?: boolean
  name: string
  priority?: number
  set_category?: string | null
  set_merchant?: string | null
  skip_ai?: boolean
}

export interface RuleOut {
  account_ref: string | null
  add_tags: string[]
  amount_max: number | null
  amount_min: number | null
  amount_sign: string | null
  created_at: string
  currency: string | null
  description_mode: string
  description_value: string
  detail_mode: string | null
  detail_value: string | null
  enabled: boolean
  id: number
  name: string
  priority: number
  set_category: string | null
  set_merchant: string | null
  skip_ai: boolean
  updated_at: string
}

export interface RulePreviewResult {
  count: number
}

export interface RuleUpdate {
  account_ref?: string | null
  add_tags?: string[] | null
  amount_max?: number | null
  amount_min?: number | null
  amount_sign?: 'negative' | 'positive' | null
  currency?: string | null
  description_mode?: 'contains' | 'starts_with' | 'exact' | 'regex' | null
  description_value?: string | null
  detail_mode?: 'contains' | 'starts_with' | 'exact' | 'regex' | null
  detail_value?: string | null
  enabled?: boolean | null
  name?: string | null
  priority?: number | null
  set_category?: string | null
  set_merchant?: string | null
  skip_ai?: boolean | null
}

export interface ScheduleOut {
  charges_from: string | null
  granularity: 'month' | 'year'
  linked: boolean
  mortgage_id: number
  rows: ScheduleRowOut[]
  total_interest: number
  total_payment: number
  total_principal: number
  years: ScheduleYearOut[]
}

export interface ScheduleRowOut {
  annual_rate: number
  charged: number | null
  closing_balance: number
  date: string
  fee: number
  interest: number
  opening_balance: number
  payment: number
  period_index: number
  prepayment: number
  principal: number
  projected: boolean
  status: 'paid' | 'elapsed' | 'pending'
}

export interface ScheduleYearOut {
  closing_balance: number
  interest: number
  months: ScheduleRowOut[]
  months_elapsed: number
  months_paid: number
  months_total: number
  payment: number
  prepayment: number
  principal: number
  year: number
}

export interface SetupIn {
  password: string
  username: string
}

export interface SimulationOut {
  after: SimulationSideOut
  alternative_gain: number | null
  amount: number
  balance_after: BalancePointOut[]
  balance_before: BalancePointOut[]
  before: SimulationSideOut
  fee: number
  implied_annual_return: number | null
  interest_saved: number
  mode: 'reduce_term' | 'reduce_payment'
  months_saved: number
  net_saving: number
  payment_delta: number
  worth_it: boolean | null
}

export interface SimulationRequest {
  alt_return_pct?: number | null
  amount: number
  fee?: number
  mode: 'reduce_term' | 'reduce_payment'
  payment_date: string
}

export interface SimulationSideOut {
  end_date: string | null
  monthly_payment: number
  months: number
  total_interest: number
  total_paid: number
}

export interface StatementMonth {
  count: number
  month: number
  year: number
}

export interface StatementOriginal {
  account_name: string
  import_run_id: number
  imported_at: string
  source_filename: string
}

export interface StatementReminderOut {
  missing_account_ids: number[]
  month: number | null
  year: number | null
}

export interface StatusResponse {
  authenticated: boolean
  initialized: boolean
}

export interface SuggestedTag {
  color: string
  name: string
}

export interface TagCreate {
  color?: string | null
  emoji?: string | null
  name: string
}

export interface TagOut {
  color: string
  emoji: string | null
  id: number
  name: string
  tx_count: number
}

export interface TagUpdate {
  color?: string | null
  emoji?: string | null
  name?: string | null
}

export interface TelegramChannelIn {
  bot_token: string
  chat_id: string
  message_thread_id?: number | null
}

export interface TelegramTestIn {
  bot_token?: string | null
  chat_id?: string | null
  message_thread_id?: number | null
}

export interface TelegramTestOut {
  error: string | null
  ok: boolean
}

export interface TopCategory {
  amount: number
  name: string
}

export interface TransactionMonthsOut {
  latest: string | null
  months: string[]
}

export interface TransactionOut {
  account: string
  amount: number
  balance_after: number | null
  category: string
  category_confidence: number | null
  currency: string
  description: string
  detail: string | null
  id: number
  is_system: boolean
  merchant: string | null
  tags: string[]
  transaction_date: string
}

export interface TransactionPage {
  items: TransactionOut[]
  limit: number
  offset: number
  total: number
}

export interface TransactionUpdate {
  amount?: number | null
  category?: string | null
  description?: string | null
  merchant?: string | null
  tags?: string[] | null
}

export interface UnreadCountOut {
  count: number
}

export interface ValidateTokenRequest {
  token: string
}

export interface ValidateTokenResponse {
  accounts: DiscoveredAccountOut[]
}

export interface ValidationError {
  ctx: Record<string, unknown>
  input: unknown
  loc: (string | number)[]
  msg: string
  type: string
}

export interface ValuePoint {
  date: string
  value: number
}

export interface VersionOut {
  built_at: string | null
  image_tag: string | null
  version: string
}
