// ─── Entity types ─────────────────────────────────────────────────────────────

export interface Account {
  id: number
  name: string
  type: string | null
  currency: string
  tx_count: number
  account_number_masked?: string | null
}

export interface AccountCreatePayload {
  name: string
  type?: string
  currency?: string
  account_number?: string | null
  opening_balance?: number | null
  opening_date?: string | null
}

export interface Category {
  id: number
  name: string
  is_base: boolean
  color: string
  name_es: string | null
  tx_count: number
}

export interface Tag {
  id: number
  name: string
  color: string
  emoji: string | null
  tx_count: number
}

export interface Transaction {
  id: number
  transaction_date: string
  amount: number          // signed: negative = expense, positive = income
  currency: string
  description: string
  category: string
  account: string
  category_confidence: number | null
  balance_after: number | null
  tags: string[]
  merchant: string | null
  detail?: string | null
  /** Synthetic opening-balance row generated by the backend (is_system=true).
   *  Visible in the ledger but excluded from all KPI/summary endpoints. */
  is_system?: boolean
}

export interface TransactionPage {
  items: Transaction[]
  total: number
  limit: number
  offset: number
}

// ─── Query param types ────────────────────────────────────────────────────────

export interface TransactionsParams {
  from?: string
  to?: string
  account_id?: number
  category_id?: number
  limit?: number
  offset?: number
  tags?: string[]
  flow?: 'expense' | 'income'
  description?: string
  amount_min?: number
  amount_max?: number
  merchant?: string
  day?: string
  sort?: string
  order?: 'asc' | 'desc'
}

export interface SummaryParams {
  from?: string
  to?: string
  account_id?: number
  category_id?: number
  tags?: string[]
  flow?: 'expense' | 'income'
  description?: string
  amount_min?: number
  amount_max?: number
  merchant?: string
  day?: string
}

// MonthSummaryParams is now identical to SummaryParams (category_id merged up)
export type MonthSummaryParams = SummaryParams

export interface DateRangeParams {
  from?: string
  to?: string
}

// ─── Response types ───────────────────────────────────────────────────────────

export interface SummaryMonths {
  months: string[]          // "YYYY-MM" sorted ascending
  latest: string | null     // last month with data, or null if empty
}

export interface Overview {
  total_expense: number   // positive magnitude
  total_income: number    // positive
  net: number             // income - expense; can be negative
  num_transactions: number
  top_category: { name: string; amount: number } | null
  currency: string
}

export interface CategorySummary {
  category: string
  category_id: number
  amount: number          // positive magnitude
  count: number
}

export interface MonthSummary {
  month: string           // "YYYY-MM"
  expense: number         // positive magnitude
  income: number          // positive
  net: number
}

export interface DaySummary {
  day: string             // "YYYY-MM-DD"
  expense: number         // positive magnitude
  income: number          // positive
  net: number
}

export interface AccountSummary {
  account: string
  expense: number         // positive magnitude
  income: number
  net: number
  currency: string
}

export interface ImportResult {
  import_run_id: number
  num_parsed: number
  num_inserted: number
  num_duplicates: number
}

export type ImportQualitySeverity = 'error' | 'warning' | 'info'

export type ImportQualitySignalCode =
  | 'low_confidence_category'
  | 'missing_category'
  | 'generic_category'
  | 'missing_merchant'
  | 'zero_amount'
  | 'date_year_mismatch'
  | 'year_undetected'
  | 'intra_batch_duplicate'

export interface ImportQualitySummary {
  error_count: number
  warning_count: number
  info_count: number
  flagged_row_count: number
}

export interface ImportQualitySignal {
  code: ImportQualitySignalCode
  severity: ImportQualitySeverity
  count: number
}

export interface ImportQualityRowFlag {
  row_index: number
  code: ImportQualitySignalCode
  severity: ImportQualitySeverity
  fields: string[]
}

export interface ImportQuality {
  summary: ImportQualitySummary
  signals: ImportQualitySignal[]
  row_flags: ImportQualityRowFlag[]
}

// ─── Import preview / confirm ─────────────────────────────────────────────────

/** Single extracted transaction — not yet persisted. */
export interface ImportTransaction {
  transaction_date: string        // "YYYY-MM-DD"
  amount: number                  // signed: negative = expense, positive = income
  currency: string
  description: string
  raw_line: string | null
  category: string
  category_confidence: number | null
  account_ref: string
  balance_after: number | null
  tags: string[]
  merchant: string | null
  detail?: string | null
  /** User override: force import even when the natural dedup key matches an existing transaction. */
  allow_duplicate?: boolean
  /** Set when a classification rule matched this line during preview. */
  matched_rule_id?: number | null
  matched_rule_name?: string | null
}

export interface PreviewResponse {
  account_ref: string | null
  filename: string
  transactions: ImportTransaction[]
  statement_year: number | null
  year_detected: boolean
  /** AI-suggested colors for tags the LLM proposed in this preview. */
  suggested_tags?: { name: string; color: string }[]
  /** Masked IBAN detected from the statement (e.g. ES****…****1332). */
  detected_account_masked?: string | null
  /** Full IBAN detected — keep in state, never display. */
  detected_account_iban?: string | null
  /** ID of an existing account that matched the detected IBAN. */
  matched_account_id?: number | null
  /** Name of the matched account, if any. */
  matched_account_name?: string | null
  /** Advisory import quality report; never blocks confirm. */
  quality: ImportQuality
}

export interface ConfirmRequest {
  account_name: string
  source_filename: string
  transactions: ImportTransaction[]
  /** Colors for brand-new tags (not yet in the DB). name→hex. */
  tag_colors?: Record<string, string>
  /** Full IBAN — only sent when creating a brand-new detected account. */
  account_number?: string | null
  /** Original PDF as base64 (data URL prefix stripped) — stored server-side for re-download. */
  source_pdf_base64?: string
  /** Opening balance for new accounts only. Server infers opening_date = day before first tx. */
  opening_balance?: number | null
}

// ─── Transaction update ───────────────────────────────────────────────────────

export interface TransactionPatch {
  description?: string
  category?: string
  amount?: number
  tags?: string[]
  merchant?: string
}

// ─── Category update ──────────────────────────────────────────────────────────

export interface CategoryPatch {
  color?: string
}

// ─── Merchant summary ────────────────────────────────────────────────────────

export interface MerchantSummary { merchant: string; amount: number; count: number }

// ─── Cashflow summary ─────────────────────────────────────────────────────────

export interface CashflowItem {
  category: string
  amount: number        // positive magnitude
}

export interface CashflowSummary {
  income: CashflowItem[]
  expense: CashflowItem[]
  total_income: number
  total_expense: number
  currency: string
}

// ─── Statements ──────────────────────────────────────────────────────────────

export interface StatementMonth {
  year: number
  month: number
  count: number
}

export interface StatementOriginal {
  import_run_id: number
  source_filename: string
  account_name: string
  imported_at: string
}

export interface StatementReminder {
  year: number | null
  month: number | null
  missing_account_ids: number[]
}

// ─── Backup ───────────────────────────────────────────────────────────────────

export interface BackupExportSelection {
  accounts: boolean
  categories: boolean
  tags: boolean
  transactions: boolean
  rules: boolean
  investments: boolean
}

export interface BackupAccountIn {
  name: string
  type: string
  currency: string
}

export interface BackupCategoryIn {
  name: string
  is_base: boolean
  color: string
  name_es?: string | null
}

export interface BackupTagIn {
  name: string
  color: string
  emoji?: string | null
}

export interface BackupTransactionIn {
  transaction_date: string
  amount: number
  currency: string
  description: string
  merchant?: string | null
  category?: string | null
  account: string
  category_confidence?: number | null
  balance_after?: number | null
  tags?: string[]
}

export interface BackupRuleIn {
  name: string
  priority?: number
  enabled?: boolean
  description_mode: string
  description_value: string
  amount_sign?: string | null
  amount_min?: number | null
  amount_max?: number | null
  account_ref?: string | null
  currency?: string | null
  detail_mode?: string | null
  detail_value?: string | null
  set_category?: string | null
  set_merchant?: string | null
  add_tags?: string[]
  skip_ai?: boolean
}

export interface BackupInvestmentConnectionIn {
  plugin_id: string
  status?: string
  account_label_masked?: string | null
  token_enc?: string | null
  last_synced_at?: string | null
}

export interface BackupEsppLotIn {
  connection_plugin_id?: string
  ticker?: string
  purchase_date: string
  grant_date?: string | null
  shares: number
  cost_basis: number
  cost_basis_per_share: number
  source_currency: string
  share_source: string
  holding_period?: string | null
  dedup_hash: string
}

export interface BackupPriceHistoryIn {
  ticker: string
  price_date: string
  close_usd: number
  fx_eur_usd: number
  close_eur: number
}

export interface BackupInvestmentsIn {
  connections?: BackupInvestmentConnectionIn[]
  espp_lots?: BackupEsppLotIn[]
  price_history?: BackupPriceHistoryIn[]
}

export interface BackupDocument {
  finlytics_backup_version: number
  exported_at: string
  accounts?: BackupAccountIn[]
  categories?: BackupCategoryIn[]
  tags?: BackupTagIn[]
  transactions?: BackupTransactionIn[]
  rules?: BackupRuleIn[]
  investments?: BackupInvestmentsIn | null
}

export interface BackupImportSummary {
  accounts_created: number
  accounts_existing: number
  categories_created: number
  categories_updated: number
  tags_created: number
  tags_updated: number
  transactions_inserted: number
  transactions_duplicates: number
  rules_created: number
  rules_updated: number
  investment_connections_created: number
  investment_connections_updated: number
  espp_lots_inserted: number
  espp_lots_duplicates: number
  price_history_inserted: number
  price_history_duplicates: number
}

// ─── Auth types ───────────────────────────────────────────────────────────────

export interface AuthStatus {
  initialized: boolean
  authenticated: boolean
}

export interface AuthUser {
  username: string
}

// ─── Rules ────────────────────────────────────────────────────────────────────

export type DescriptionMode = 'contains' | 'starts_with' | 'exact' | 'regex'
export type AmountSign = 'negative' | 'positive'

export interface Rule {
  id: number
  name: string
  priority: number
  enabled: boolean
  description_mode: DescriptionMode
  description_value: string
  detail_mode?: DescriptionMode | null
  detail_value?: string | null
  amount_sign: AmountSign | null
  amount_min?: number | null
  amount_max?: number | null
  account_ref: string | null
  currency: string | null
  set_category: string | null
  set_merchant: string | null
  add_tags: string[]
  skip_ai: boolean
  created_at: string
  updated_at: string
}

export interface RuleInput {
  name: string
  priority?: number
  enabled?: boolean
  description_mode: DescriptionMode
  description_value: string
  detail_mode?: DescriptionMode | null
  detail_value?: string | null
  amount_sign?: AmountSign | null
  amount_min?: number | null
  amount_max?: number | null
  account_ref?: string | null
  currency?: string | null
  set_category?: string | null
  set_merchant?: string | null
  add_tags?: string[]
  skip_ai?: boolean
}

export interface RulePatch {
  name?: string
  priority?: number
  enabled?: boolean
  description_mode?: DescriptionMode
  description_value?: string
  detail_mode?: DescriptionMode | null
  detail_value?: string | null
  amount_sign?: AmountSign | null
  amount_min?: number | null
  amount_max?: number | null
  account_ref?: string | null
  currency?: string | null
  set_category?: string | null
  set_merchant?: string | null
  add_tags?: string[]
  skip_ai?: boolean
}

// ─── UI types ─────────────────────────────────────────────────────────────────

export interface GlobalFilters {
  from: string
  to: string
  account_id?: number
  category_id?: number
  tags: string[]
  flow?: 'expense' | 'income'
  merchant?: string
  day?: string
}

/** Superset of GlobalFilters used by the Transactions full-page view. */
export interface TransactionsViewFilters extends GlobalFilters {
  description?: string
  amount_min?: number
  amount_max?: number
  merchant?: string
}

// ─── Investments ──────────────────────────────────────────────────────────────

export interface InvestmentPlugin {
  id: string
  name: string
  description: string
  icon: string
  status: 'coming_soon' | 'available' | 'connected' | 'error'
  auth_type: 'api_key' | 'oauth' | 'token' | 'none'
  supported_features: string[]
  /** Non-null for plugins that support CSV/file import; value is the import page route (e.g. '/investments/fidelity-espp'). Added by Shuri. */
  import_route: string | null
}

export interface InvestmentReturns {
  twr_annual: number | null
  xirr: number | null
  pl: number | null
  invested: number | null
  twr_total?: number | null
  twr_last_week?: number | null
  twr_last_month?: number | null
  twr_last_year?: number | null
  money_return?: number | null
  volatility?: number | null
  // Indexa redesign fields
  aportaciones?: number | null
  retenciones?: number | null
  rentabilidad_eur?: number | null
  rentabilidad_pct?: number | null
  sharpe_ratio?: number | null
  money_return_annual?: number | null
}

export interface ValuePoint {
  date: string    // "YYYY-MM-DD"
  value: number
}

export interface MonthlyReturnRow {
  year: number
  months_pct: Record<string, number | null | undefined>
  months_eur: Record<string, number | null | undefined>
  total_pct: number | null
  total_eur: number | null
  benchmark_pct: number | null
}

export interface DrawdownOut {
  max_drawdown: number
  max_drawdown_eur: number
  start_date: string    // "YYYY-MM-DD"
  end_date: string      // "YYYY-MM-DD"
}

export interface CashInvestedSplit {
  cash_amount: number
  instruments_amount: number
  instruments_cost: number
  total_amount: number
}

export interface InvestmentHolding {
  plugin_id: string
  name: string
  ticker: string
  asset_class: string
  units: number
  current_value: number
  cost_basis: number
  currency: string
  gain_loss: number
  gain_loss_pct: number    // decimal: 0.1093 = 10.93%
  last_updated: string
}

export interface ContributionEvent {
  date: string
  amount: number       // signed: + = contribution, − = withdrawal
  cumulative: number
  type: 'contribution' | 'withdrawal'
}

export interface InvestmentPortfolio {
  total_value: number
  total_invested: number | null
  total_gain_loss: number | null
  total_gain_loss_pct: number | null   // decimal
  currency: string
  plugins_connected: number
  last_updated: string | null
  returns: InvestmentReturns | null
  value_series: ValuePoint[]
  contributions_series: ValuePoint[]
  monthly_returns: MonthlyReturnRow[] | null
  drawdown: DrawdownOut | null
  cash_invested: CashInvestedSplit | null
  holdings: InvestmentHolding[]
  contribution_events?: ContributionEvent[]
}

export interface InvestmentConnection {
  id: number
  plugin_id: string
  status: 'active' | 'error' | 'disconnected'
  account_label_masked: string | null
  created_at: string
  last_synced_at: string | null
}

export interface ValidatedAccount {
  account_number: string
  account_number_masked: string
  type: string
  status: string
}

export interface ValidateAccountsResponse {
  accounts: ValidatedAccount[]
}

// ─── Fidelity ESPP ────────────────────────────────────────────────────────────

export interface FidelityReminderResponse {
  overdue: boolean
  expected_date: string | null      // "YYYY-MM-DD"
  period_label: string | null       // e.g. "Q2 2026"
  last_lot_date: string | null      // "YYYY-MM-DD"
}

export interface FidelityKpis {
  total_shares: number
  invested_eur: number
  current_value_eur: number | null
  gain_loss_eur: number | null
  gain_loss_pct: number | null
  msft_price_usd: number | null
  usd_eur_rate: number | null
  last_price_date: string | null   // "YYYY-MM-DD"
  price_stale: boolean
  as_of_date: string               // "YYYY-MM-DD"
}

export interface FidelityEvolution {
  value_series: ValuePoint[]
  contributions_series: ValuePoint[]
}

export interface FidelityLot {
  id: number
  purchase_date: string            // "YYYY-MM-DD"
  shares: number
  cost_basis_per_share_eur: number
  cost_basis_total_eur: number
  current_value_eur: number | null
  gain_loss_eur: number | null
  gain_loss_pct: number | null     // percentage: 12.5 = 12.5%
  share_source: 'SP' | 'DO'
  grant_date: string | null        // "YYYY-MM-DD"
}

export interface FidelityLots {
  lots: FidelityLot[]
}

export interface FidelityImportPreviewLot {
  purchase_date: string
  shares: number
  cost_basis_per_share_eur: number
  cost_basis_total_eur: number
  share_source: 'SP' | 'DO'
  grant_date: string | null
}

export interface FidelityImportPreview {
  new_lots: FidelityImportPreviewLot[]
  duplicate_count: number
  total_in_file: number
  source_currency: string
  file_already_imported: boolean
}

export interface FidelityImportConfirmResult {
  inserted: number
  duplicates: number
}

// ─── App version ─────────────────────────────────────────────────────────────

export interface AppVersion {
  version: string
  image_tag: string | null
  built_at: string | null
}

// ─── Combined investments overview ────────────────────────────────────────────

export interface CombinedOverviewProviderSlice {
  provider: string
  label: string
  value_eur: number
  pct: number
}

export interface CombinedOverviewAssetClassSlice {
  asset_class: string
  label: string
  value_eur: number
  pct: number
}

export interface CombinedOverviewProvider {
  id: string
  name: string
  icon: string
  value_eur: number | null
  gain_loss_eur: number | null
  gain_loss_pct: number | null
  route: string
}

export interface CombinedOverview {
  total_value_eur: number
  total_invested_eur: number | null
  total_gain_loss_eur: number | null
  total_gain_loss_pct: number | null
  by_provider: CombinedOverviewProviderSlice[]
  by_asset_class: CombinedOverviewAssetClassSlice[]
  providers: CombinedOverviewProvider[]
}

// ─── Notifications ────────────────────────────────────────────────────────────

export interface NotificationOut {
  id: number
  source: string
  type: string
  severity: 'info' | 'warning'
  title_key: string
  title_args: Record<string, string | number>
  body_key: string | null
  body_args: Record<string, unknown> | null
  action_link: string | null
  created_at: string
  read_at: string | null
  dismissed_at: string | null
}

// ─── Notification channels ────────────────────────────────────────────────────

export interface NotificationChannelOut {
  id: number
  channel: string
  label: string | null
  enabled: boolean
  created_at: string
}

export interface TelegramChannelIn {
  bot_token: string
  chat_id: string
  message_thread_id?: number | null
}

export interface TelegramTestIn {
  bot_token?: string
  chat_id?: string
  message_thread_id?: number | null
}

export interface TelegramTestOut {
  ok: boolean
  error?: string
}

// ─── Finance assistant ────────────────────────────────────────────────────────

export interface AssistantStatus {
  enabled: boolean
  reason: string | null
}

export interface AssistantSuggestions {
  suggestions: string[]
}

/** Audit record of a query the assistant ran while composing an answer. */
export interface AssistantToolCall {
  name: string
  arguments: string
  ok: boolean
}

export interface AssistantMessage {
  id: number
  role: 'user' | 'assistant'
  content: string
  tool_calls: AssistantToolCall[] | null
  created_at: string
}

export interface AssistantConversation {
  id: number
  title: string
  created_at: string
  updated_at: string
}

export interface AssistantConversationDetail extends AssistantConversation {
  messages: AssistantMessage[]
}

/** One frame of the SSE answer stream. Mirrors the backend's event names. */
export type AssistantStreamEvent =
  | { type: 'tool'; name: string; label: string }
  | { type: 'token'; text: string }
  | { type: 'done'; message_id: number; title: string; total_tokens: number | null }
  | { type: 'error'; detail: string }

// ─── Assistant settings and usage ─────────────────────────────────────────────

export interface AssistantSettings {
  /** null means "no override" — the shipped default applies. */
  custom_instructions: string | null
  /** null means "use the shipped prompt". */
  system_prompt: string | null
  rate_limit_messages: number | null
  rate_limit_window_seconds: number | null
  monthly_token_budget: number | null

  /** What is actually in force once the shipped defaults are resolved. */
  effective_rate_limit_messages: number
  effective_rate_limit_window_seconds: number
  max_custom_instructions_chars: number

  /** The shipped prompt, for pre-filling the editor and the restore button. */
  default_system_prompt: string
  max_system_prompt_chars: number
  /** Safety rules a customised prompt no longer contains. Advisory only. */
  missing_safety_markers: string[]
}

export interface AssistantSettingsPayload {
  custom_instructions?: string | null
  system_prompt?: string | null
  rate_limit_messages?: number | null
  rate_limit_window_seconds?: number | null
  monthly_token_budget?: number | null
}

export interface AssistantUsagePeriod {
  prompt_tokens: number
  completion_tokens: number
  total_tokens: number
  messages: number
}

export interface AssistantUsageDay {
  day: string
  tokens: number
  messages: number
}

export interface AssistantUsage {
  this_month: AssistantUsagePeriod
  all_time: AssistantUsagePeriod
  by_day: AssistantUsageDay[]
  monthly_token_budget: number | null
  budget_remaining: number | null
  /** False when the provider never reports usage, so the UI can say "unknown"
   *  rather than showing a confident zero. */
  usage_available: boolean
}

// ─── Mortgage ─────────────────────────────────────────────────────────────────

export type MortgageRateType = 'fixed' | 'variable' | 'mixed'
export type MortgageRateKind = 'fixed' | 'variable'
export type PrepaymentMode = 'reduce_term' | 'reduce_payment'

export interface MortgageRatePeriod {
  id?: number
  start_month: number
  kind: MortgageRateKind
  fixed_rate?: number | null
  index_name?: string | null
  spread?: number | null
  review_months?: number | null
  review_lag_months: number
  floor_rate?: number | null
  cap_rate?: number | null
}

export interface MortgageBonus {
  id?: number
  name: string
  spread_reduction: number
  annual_cost: number
  active: boolean
  start_date?: string | null
  end_date?: string | null
}

export interface MortgagePrepayment {
  id: number
  payment_date: string
  amount: number
  mode: PrepaymentMode
  fee: number
  notes?: string | null
}

export interface MortgagePrepaymentInput {
  payment_date: string
  amount: number
  mode: PrepaymentMode
  fee?: number
  notes?: string | null
}

export interface MortgageInput {
  name: string
  lender?: string | null
  initial_principal: number
  start_date: string
  term_months: number
  payment_day: number
  rate_type: MortgageRateType
  linked_account_id?: number | null
  linked_category_id?: number | null
  property_value?: number | null
  property_value_date?: string | null
  include_in_net_worth: boolean
  notes?: string | null
  rate_periods: MortgageRatePeriod[]
  bonuses: MortgageBonus[]
}

export interface Mortgage extends MortgageInput {
  id: number
  rate_periods: MortgageRatePeriod[]
  bonuses: MortgageBonus[]
  prepayments: MortgagePrepayment[]
}

export interface MortgageSummary {
  id: number
  name: string
  lender: string | null
  rate_type: MortgageRateType
  outstanding_balance: number
  monthly_payment: number
  progress_pct: number
}

export interface MortgageOverview {
  id: number
  name: string
  lender: string | null
  rate_type: MortgageRateType
  initial_principal: number
  outstanding_balance: number
  amortized_principal: number
  progress_pct: number
  current_payment: number
  current_rate: number
  next_payment_date: string | null
  interest_paid: number
  interest_remaining: number
  total_interest: number
  total_cost: number
  months_elapsed: number
  months_remaining: number
  end_date: string | null
  original_end_date: string | null
  months_saved: number
  interest_saved: number
  property_value: number | null
  ltv_pct: number | null
  total_prepaid: number
  annual_bonus_cost: number
  has_projection: boolean
  include_in_net_worth: boolean
  linked_account_id: number | null
  linked_category_id: number | null
}

export interface MortgageScheduleRow {
  period_index: number
  date: string
  opening_balance: number
  payment: number
  interest: number
  principal: number
  prepayment: number
  fee: number
  closing_balance: number
  annual_rate: number
  projected: boolean
}

export interface MortgageScheduleYear {
  year: number
  payment: number
  interest: number
  principal: number
  prepayment: number
  closing_balance: number
  months: MortgageScheduleRow[]
}

export interface MortgageSchedule {
  mortgage_id: number
  granularity: 'month' | 'year'
  rows: MortgageScheduleRow[]
  years: MortgageScheduleYear[]
  total_payment: number
  total_interest: number
  total_principal: number
}

export interface MortgageBalancePoint {
  date: string
  balance: number
  projected: boolean
}

export interface MortgageCharts {
  balance: MortgageBalancePoint[]
  composition: MortgageScheduleYear[]
}

export interface EuriborPoint {
  period: string
  rate: number
}

export interface EuriborSeries {
  index_name: string
  points: EuriborPoint[]
  latest: number | null
  latest_period: string | null
}

export interface MortgageReconciliationRow {
  period: string
  expected: number
  actual: number | null
  deviation: number | null
  deviation_pct: number | null
  matched: boolean
}

export interface MortgageReconciliation {
  mortgage_id: number
  linked: boolean
  account_id: number | null
  category_id: number | null
  rows: MortgageReconciliationRow[]
  total_expected: number
  total_actual: number
}

export interface MortgageSimulationRequest {
  amount: number
  payment_date: string
  mode: PrepaymentMode
  fee?: number
  alt_return_pct?: number | null
}

export interface MortgageSimulationSide {
  months: number
  end_date: string | null
  total_interest: number
  total_paid: number
  monthly_payment: number
}

export interface MortgageSimulation {
  before: MortgageSimulationSide
  after: MortgageSimulationSide
  amount: number
  fee: number
  mode: PrepaymentMode
  interest_saved: number
  months_saved: number
  payment_delta: number
  net_saving: number
  implied_annual_return: number | null
  alternative_gain: number | null
  worth_it: boolean | null
  balance_before: MortgageBalancePoint[]
  balance_after: MortgageBalancePoint[]
}

export interface MortgageNetWorth {
  outstanding_debt: number
  property_value: number
  net_contribution: number
  count: number
}

export interface MortgagePaymentCandidate {
  account_id: number
  account_name: string
  category_id: number | null
  category_name: string | null
  amount: number
  months_matched: number
  first_seen: string
  last_seen: string
  deviation: number | null
  deviation_pct: number | null
}

export interface MortgagePaymentCandidates {
  expected_payment: number | null
  candidates: MortgagePaymentCandidate[]
}
